apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-postgres
  labels:
    app: infra-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-postgres
  template:
    metadata:
      labels:
        app: infra-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            # PostgreSQL configuration
            - name: POSTGRES_DB
              value: 'microservices_db'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: PGDATA
              value: '/var/lib/postgresql/data/pgdata'
            # Health check
            - name: POSTGRES_INITDB_ARGS
              value: '--auth-host=scram-sha-256'
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 5
        volumes:
          - name: postgres-storage
            persistentVolumeClaim:
              claimName: postgres-pvc
