apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: infra-postgres
spec:
  accessModes:
    - ReadWriteOnce # Single node access (PostgreSQL requirement)
  resources:
    requests:
      storage: 10Gi # 10GB storage for database
  storageClassName: local-path # Use local-path storage class
