apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mon-grafana-pvc
  labels:
    app: mon-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
