apiVersion: v1
kind: Service
metadata:
  name: mon-grafana
  labels:
    app: mon-grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: mon-grafana
