apiVersion: v1
kind: Service
metadata:
  name: app-auth
  labels:
    app: app-auth
spec:
  selector:
    app: app-auth
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
