apiVersion: v1
kind: Service
metadata:
  name: app-books
  labels:
    app: app-books
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: app-books
