apiVersion: v1
kind: Service
metadata:
  name: infra-redis
  labels:
    app: infra-redis
spec:
  selector:
    app: infra-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
