apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-jaeger
  labels:
    app: mon-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-jaeger
  template:
    metadata:
      labels:
        app: mon-jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686  # Jaeger UI
            - containerPort: 14268 # Jaeger collector
            - containerPort: 14250 # Jaeger agent
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: "9411"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 5
            periodSeconds: 5
