apiVersion: v1
kind: Service
metadata:
  name: mon-jaeger
  labels:
    app: mon-jaeger
spec:
  selector:
    app: mon-jaeger
  ports:
    - name: jaeger-ui
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: jaeger-collector
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: jaeger-agent
      protocol: TCP
      port: 14250
      targetPort: 14250
  type: ClusterIP
